#!/usr/bin/env node
// Verifies that the committed site in apps/web matches the sources in web/ and
// that every page keeps the SEO contract: canonical URL, description, share
// image, valid structured data and working internal links.
import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { gzipSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import { buildSite } from '../web/build.mjs';

const outputDir = fileURLToPath(new URL('../apps/web', import.meta.url));
const errors = [];
const warnings = [];
const { files } = buildSite();

// --- 1. Committed output must match the sources ----------------------------
for (const [path, contents] of files) {
  const target = resolve(outputDir, `.${path}`);
  if (!existsSync(target)) {
    errors.push(`${path} is missing on disk. Run npm run web:build.`);
    continue;
  }
  if (readFileSync(target, 'utf8') !== contents) {
    errors.push(`${path} is out of date. Run npm run web:build.`);
  }
}

const generated = new Set([...files.keys()]);
for (const file of walk(outputDir)) {
  const path = `/${relative(outputDir, file).split(/[\\/]/).join('/')}`;
  const isGeneratedType = file.endsWith('.html') || file.endsWith('.xml') || file.endsWith('site.webmanifest');
  if (isGeneratedType && !generated.has(path)) {
    errors.push(`${path} is no longer generated by the build. Run npm run web:build.`);
  }
}

function walk(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
    const full = join(dir, entry.name);
    return entry.isDirectory() ? walk(full) : [full];
  });
}

const diskAssets = new Set(
  walk(outputDir)
    .map(file => relative(outputDir, file).split(/[\\/]/).join('/'))
    .filter(path => !path.endsWith('.html') && !path.endsWith('.xml'))
    .map(path => `/${path}`),
);

// --- 2. Per page checks ----------------------------------------------------
const required = ['<title>', 'name="description"', 'rel="canonical"', 'property="og:image"', 'name="viewport"'];

for (const [path, contents] of files) {
  if (!path.endsWith('.html')) continue;

  for (const needle of required) {
    if (!contents.includes(needle)) errors.push(`${path} is missing ${needle}`);
  }

  const title = /<title>([\s\S]*?)<\/title>/.exec(contents)?.[1] ?? '';
  if (title.length > 75) warnings.push(`${path} title is ${title.length} characters long`);

  const description = /<meta name="description" content="([^"]*)"/.exec(contents)?.[1] ?? '';
  if (description.length < 80 || description.length > 175) {
    warnings.push(`${path} description is ${description.length} characters long`);
  }

  const h1Count = (contents.match(/<h1[\s>]/g) ?? []).length;
  if (h1Count !== 1) errors.push(`${path} has ${h1Count} <h1> elements`);

  // Article bodies are hand written HTML inside a template; an unbalanced tag
  // silently wrecks the layout of everything that follows it.
  for (const tag of ['div', 'p', 'ul', 'ol', 'li', 'table', 'tr', 'td', 'strong', 'h2', 'h3', 'section', 'nav']) {
    const opened = (contents.match(new RegExp(`<${tag}(?=[ >])`, 'g')) ?? []).length;
    const closed = (contents.match(new RegExp(`</${tag}>`, 'g')) ?? []).length;
    if (opened !== closed) {
      errors.push(`${path} has ${opened} <${tag}> and ${closed} </${tag}>: the markup is unbalanced`);
    }
  }

  const canonical = /<link rel="canonical" href="([^"]+)"/.exec(contents)?.[1];
  if (!canonical?.startsWith('https://')) errors.push(`${path} has no absolute canonical URL`);

  for (const match of contents.matchAll(/<img\b[^>]*>/g)) {
    if (!/\balt="/.test(match[0])) errors.push(`${path} has an <img> without alt text: ${match[0].slice(0, 80)}`);
  }

  for (const match of contents.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) {
    try {
      JSON.parse(match[1]);
    } catch (error) {
      errors.push(`${path} has invalid JSON-LD: ${error.message}`);
    }
  }

  for (const match of contents.matchAll(/(?:href|src)="(\/[^"#?]*)"/g)) {
    const reference = match[1];
    const target = reference.endsWith('/') ? `${reference}index.html` : reference;
    if (!generated.has(target) && !diskAssets.has(target)) {
      errors.push(`${path} links to ${reference}, which does not exist`);
    }
  }

  // Social preview images are referenced from content attributes, not src.
  for (const match of contents.matchAll(/property="og:image" content="[^"]*?(\/img\/[^"]+)"/g)) {
    if (!diskAssets.has(match[1])) {
      errors.push(`${path} has no share image at ${match[1]}. Run npm run web:assets.`);
    }
  }
}

const describe = path => `  ${path}`;

// --- 3. Sitemap must list exactly the indexable pages ----------------------
const sitemap = files.get('/sitemap.xml');
const listed = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(match => match[1].replace('https://www.empezar-a-invertir.com', ''));
const expectedUrls = [...files.keys()]
  .filter(path => path.endsWith('.html'))
  .map(path => (path === '/index.html' ? '/' : path.replace(/index\.html$/, '').replace(/\.html$/, '.html')))
  .filter(url => url !== '/404.html');

for (const url of expectedUrls) {
  if (!listed.includes(url)) errors.push(`sitemap.xml is missing ${url}`);
}
for (const url of listed) {
  if (!expectedUrls.includes(url)) errors.push(`sitemap.xml lists ${url}, which is not a page`);
}

// --- 4. WebGPU background ------------------------------------------------
// The shader bundle is committed, so the checks only need Node: they verify the
// artifact exists, stays inside its budget, is self-contained and was built from
// the shader sources that are in the repository.
const gpuFiles = { loader: '/js/webgpu.js', bundle: '/js/webgpu-effect.js' };
const gpuBudget = { raw: 220 * 1024, gzip: 60 * 1024 };

for (const [name, path] of Object.entries(gpuFiles)) {
  if (!diskAssets.has(path)) errors.push(`The WebGPU ${name} is missing at ${path}. Run npm run web:gpu.`);
}

if (diskAssets.has(gpuFiles.bundle)) {
  const bundle = readFileSync(join(outputDir, gpuFiles.bundle.slice(1)));
  const source = readFileSync(fileURLToPath(new URL('../web/gpu/effect.js', import.meta.url)));
  const hash = createHash('sha256').update(source).digest('hex').slice(0, 16);
  const gzip = gzipSync(bundle).length;

  if (!bundle.includes(`source=${hash}`)) {
    errors.push(`${gpuFiles.bundle} was built from an older web/gpu/effect.js. Run npm run web:gpu.`);
  }
  if (bundle.length > gpuBudget.raw || gzip > gpuBudget.gzip) {
    errors.push(`${gpuFiles.bundle} exceeds the budget: ${bundle.length} B raw / ${gzip} B gzip.`);
  }
  // Error messages may quote a documentation URL; what must never appear is a
  // network load, because everything ships from this origin.
  if (/(?:import\s*\(\s*|fetch\s*\(\s*|src\s*=\s*)["'`]https?:/.test(bundle.toString('utf8'))) {
    errors.push(`${gpuFiles.bundle} must stay self-contained and load nothing from the network.`);
  }
}

// --- 5. Report -------------------------------------------------------------
if (warnings.length) {
  console.log(`Warnings (${warnings.length}):\n${warnings.map(describe).join('\n')}`);
}

if (errors.length) {
  console.error(`Web checks failed (${errors.length}):\n${errors.map(describe).join('\n')}`);
  process.exit(1);
}

const pageCount = [...files.keys()].filter(path => path.endsWith('.html')).length;
console.log(`Web site verified: ${pageCount} pages, ${listed.length} sitemap entries, all internal links resolve.`);
