// Article metadata for the static site build.
// Bodies live in web/articles/<slug>.html and stay in plain HTML so they can be
// edited without touching the generator.

export const categories = [
  {
    name: 'Primeros pasos',
    description: 'Cómo pasar de la intención a la primera aportación sin cometer errores caros.',
  },
  {
    name: 'Conceptos básicos',
    description: 'El vocabulario imprescindible para entender qué estás haciendo con tu dinero.',
  },
  {
    name: 'Dónde invertir',
    description: 'Productos, plataformas y alternativas comparadas con criterio.',
  },
  {
    name: 'Inversión en España',
    description: 'Fiscalidad, plataformas y particularidades de invertir desde España.',
  },
];

export const articles = [
  {
    slug: 'como-empezar-a-invertir-desde-cero',
    title: 'Cómo empezar a invertir desde cero',
    seoTitle: 'Cómo empezar a invertir desde cero: guía paso a paso',
    description: 'Guía paso a paso para principiantes que no saben por dónde empezar a invertir. Define objetivos, perfil de riesgo, fondo de emergencia y primeros pasos prácticos.',
    category: 'Primeros pasos',
    published: '2025-05-01',
    updated: '2026-09-10',
    minutes: 12,
    illustration: 'steps',
    cta: {
      title: '¿Te has quedado con ganas de más?',
      body: 'Profundiza en todos estos conceptos con nuestra Guía para Empezar a Invertir. Escrita con el mismo lenguaje claro y directo.',
    },
    related: ['como-invertir-con-poco-dinero', 'donde-invertir-mi-dinero-opciones-novatos', 'guia-basica-invertir-espana'],
  },
  {
    slug: 'como-invertir-con-poco-dinero',
    title: 'Cómo invertir con poco dinero',
    seoTitle: 'Cómo invertir con poco dinero | Empieza con 50€ al mes',
    description: 'No necesitas ser rico para invertir. Descubre cómo empezar a invertir con 50€ o 100€ al mes gracias a fondos indexados, roboadvisors y la estrategia DCA.',
    category: 'Primeros pasos',
    published: '2025-05-01',
    updated: '2026-09-10',
    minutes: 7,
    illustration: 'compound',
    cta: {
      title: 'Aprende más sobre el interés compuesto y la inversión periódica',
      body: 'Nuestra guía te explica estos conceptos con más detalle y te enseña cómo ponerlos en práctica.',
    },
    related: ['como-empezar-a-invertir-desde-cero', 'donde-invertir-mi-dinero-opciones-novatos', 'diferencia-entre-activos-y-pasivos'],
  },
  {
    slug: 'cuanto-dinero-necesito-para-invertir',
    title: 'Cuánto dinero necesito para empezar a invertir',
    seoTitle: 'Cuánto dinero necesito para empezar a invertir en 2026',
    description: 'Descubre cuánto dinero necesitas realmente para empezar a invertir. Cantidades mínimas por producto, plataformas accesibles en España y el poder de las aportaciones pequeñas.',
    category: 'Primeros pasos',
    published: '2026-04-07',
    updated: '2026-09-10',
    minutes: 10,
    illustration: 'practice',
    cta: {
      title: 'Tu primer paso hacia la inversión inteligente',
      body: 'La Guía para Empezar a Invertir te acompaña desde cero, con ejemplos prácticos, comparativas de plataformas y plantillas de ahorro para empezar con cualquier presupuesto.',
    },
    related: ['como-invertir-con-poco-dinero', 'que-es-el-interes-compuesto', 'que-es-un-roboadvisor'],
  },
  {
    slug: 'diferencia-entre-activos-y-pasivos',
    title: 'Diferencia entre activos y pasivos',
    seoTitle: 'Diferencia entre activos y pasivos con ejemplos',
    description: 'Aprende qué son activos y pasivos con ejemplos claros. Entiende por qué esta distinción es vital para tus finanzas personales y la construcción de riqueza.',
    category: 'Conceptos básicos',
    published: '2025-05-01',
    updated: '2026-09-10',
    minutes: 6,
    illustration: 'concepts',
    cta: {
      title: 'Aprende más conceptos financieros esenciales',
      body: 'En nuestra guía cubrimos activos, pasivos, inflación, interés compuesto, diversificación y mucho más, todo explicado sin jerga financiera.',
    },
    related: ['como-empezar-a-invertir-desde-cero', 'como-invertir-con-poco-dinero', 'donde-invertir-mi-dinero-opciones-novatos'],
  },
  {
    slug: 'donde-invertir-mi-dinero-opciones-novatos',
    title: '¿Dónde invertir mi dinero? Opciones para principiantes',
    seoTitle: '¿Dónde invertir mi dinero? Opciones para principiantes',
    description: 'Un repaso a las opciones más comunes para empezar a invertir: cuentas remuneradas, fondos indexados, roboadvisors, acciones, bonos y más. Ventajas y riesgos de cada una.',
    category: 'Dónde invertir',
    published: '2025-05-01',
    updated: '2026-09-10',
    minutes: 10,
    illustration: 'diversification',
    cta: {
      title: '¿Quieres entender mejor cada opción?',
      body: 'La Guía para Empezar a Invertir te lo explica todo con más detalle, sin tecnicismos.',
    },
    related: ['como-empezar-a-invertir-desde-cero', 'como-invertir-con-poco-dinero', 'diferencia-entre-activos-y-pasivos'],
  },
  {
    slug: 'errores-comunes-invertir-principiantes',
    title: '9 errores comunes al invertir siendo principiante',
    seoTitle: '9 errores comunes al invertir siendo principiante',
    description: 'Descubre los errores más habituales que cometen los inversores principiantes y aprende a evitarlos. Desde vender en pánico hasta ignorar las comisiones.',
    category: 'Primeros pasos',
    published: '2026-04-07',
    updated: '2026-09-10',
    minutes: 12,
    illustration: 'risk',
    cta: {
      title: 'Empieza a invertir con buen pie',
      body: 'La Guía para Empezar a Invertir te da las herramientas y el conocimiento para evitar los errores más caros y construir un patrimonio con criterio.',
    },
    related: ['como-empezar-a-invertir-desde-cero', 'fondo-de-emergencia-cuanto-necesito', 'que-es-la-diversificacion'],
  },
  {
    slug: 'fondo-de-emergencia-cuanto-necesito',
    title: 'Fondo de emergencia: cuánto necesito y dónde guardarlo',
    seoTitle: 'Fondo de emergencia: cuánto necesito y dónde guardarlo',
    description: 'Aprende qué es un fondo de emergencia, cómo calcular cuánto necesitas, dónde guardarlo y por qué es imprescindible antes de empezar a invertir.',
    category: 'Primeros pasos',
    published: '2026-04-07',
    updated: '2026-09-10',
    minutes: 10,
    illustration: 'emergency',
    cta: {
      title: 'Tu plan financiero completo, paso a paso',
      body: 'La Guía para Empezar a Invertir cubre todo: desde el fondo de emergencia hasta tu primera cartera de inversión. Sin humo, sin promesas irreales.',
    },
    related: ['como-empezar-a-invertir-desde-cero', 'que-es-la-inflacion-como-afecta-ahorros', 'como-invertir-con-poco-dinero'],
  },
  {
    slug: 'guia-basica-invertir-espana',
    title: 'Guía básica para invertir en España',
    seoTitle: 'Guía básica para invertir en España',
    description: '¿Inviertes desde España? Conoce las opciones disponibles, las mejores plataformas, los aspectos fiscales clave y cómo empezar a invertir en el mercado español.',
    category: 'Inversión en España',
    published: '2025-05-01',
    updated: '2026-09-10',
    minutes: 10,
    illustration: 'book',
    cta: {
      title: '¿Quieres una guía completa paso a paso?',
      body: 'Nuestro libro te lleva de la mano en el proceso de empezar a invertir, con lenguaje claro y sin tecnicismos.',
    },
    related: ['como-empezar-a-invertir-desde-cero', 'donde-invertir-mi-dinero-opciones-novatos', 'como-invertir-con-poco-dinero'],
  },
  {
    slug: 'que-es-el-interes-compuesto',
    title: 'Qué es el interés compuesto y cómo funciona',
    seoTitle: 'Qué es el interés compuesto y cómo funciona',
    description: 'Entiende qué es el interés compuesto, cómo funciona el efecto bola de nieve, ejemplos con números reales y por qué empezar a invertir pronto marca una diferencia enorme.',
    category: 'Conceptos básicos',
    published: '2026-04-07',
    updated: '2026-09-10',
    minutes: 9,
    illustration: 'compound',
    cta: {
      title: 'Aprende a poner el interés compuesto de tu lado',
      body: 'La Guía para Empezar a Invertir te explica con ejemplos prácticos cómo construir un plan de inversión que aproveche esta fuerza imparable.',
    },
    related: ['que-es-la-inflacion-como-afecta-ahorros', 'que-es-un-fondo-indexado', 'como-empezar-a-invertir-desde-cero'],
  },
  {
    slug: 'que-es-la-diversificacion',
    title: 'Qué es la diversificación en inversiones',
    seoTitle: 'Qué es la diversificación en inversiones',
    description: 'Aprende qué es la diversificación de inversiones, por qué reduce el riesgo de tu cartera y cómo diversificar aunque tengas poco dinero. Guía para principiantes.',
    category: 'Conceptos básicos',
    published: '2026-04-07',
    updated: '2026-09-10',
    minutes: 11,
    illustration: 'diversification',
    cta: {
      title: 'Construye una cartera diversificada con confianza',
      body: 'En la Guía para Empezar a Invertir te enseñamos a diversificar de verdad, con ejemplos prácticos y plantillas de cartera adaptadas a tu perfil.',
    },
    related: ['renta-fija-vs-renta-variable', 'que-es-un-fondo-indexado', 'errores-comunes-invertir-principiantes'],
  },
  {
    slug: 'que-es-la-inflacion-como-afecta-ahorros',
    title: 'Qué es la inflación y cómo afecta a tus ahorros',
    seoTitle: 'Qué es la inflación y cómo afecta a tus ahorros',
    description: 'Entiende qué es la inflación, cómo erosiona el poder adquisitivo de tus ahorros y por qué invertir es la mejor forma de proteger tu dinero a largo plazo.',
    category: 'Conceptos básicos',
    published: '2026-04-07',
    updated: '2026-09-10',
    minutes: 9,
    illustration: 'inflation',
    cta: {
      title: 'Que tu dinero no pierda valor',
      body: 'La Guía para Empezar a Invertir te explica, paso a paso, cómo proteger tus ahorros de la inflación y hacer que crezcan con el tiempo.',
    },
    related: ['que-es-el-interes-compuesto', 'fondo-de-emergencia-cuanto-necesito', 'diferencia-entre-activos-y-pasivos'],
  },
  {
    slug: 'que-es-un-etf',
    title: 'Qué es un ETF y cómo funciona',
    seoTitle: 'Qué es un ETF: guía completa para principiantes',
    description: 'Aprende qué es un ETF, cómo funciona, en qué se diferencia de un fondo indexado, sus ventajas e inconvenientes, y cómo comprar ETFs en España. Guía para principiantes.',
    category: 'Conceptos básicos',
    published: '2026-04-07',
    updated: '2026-09-10',
    minutes: 12,
    illustration: 'markets',
    cta: {
      title: 'Elige los productos adecuados para tu cartera',
      body: 'En la Guía para Empezar a Invertir comparamos ETFs, fondos indexados y roboadvisors con detalle para que tomes la mejor decisión según tu situación.',
    },
    related: ['que-es-un-fondo-indexado', 'renta-fija-vs-renta-variable', 'donde-invertir-mi-dinero-opciones-novatos'],
  },
  {
    slug: 'que-es-un-fondo-indexado',
    title: 'Qué es un fondo indexado y cómo funciona',
    seoTitle: 'Qué es un fondo indexado y cómo funciona',
    description: 'Descubre qué es un fondo indexado, cómo funciona, por qué es la opción favorita de los inversores a largo plazo y cómo invertir en fondos indexados desde España.',
    category: 'Conceptos básicos',
    published: '2026-04-07',
    updated: '2026-09-10',
    minutes: 10,
    illustration: 'concepts',
    cta: {
      title: 'Aprende a construir tu cartera de fondos indexados',
      body: 'En la Guía para Empezar a Invertir te explicamos paso a paso cómo elegir tus fondos, dónde comprarlos y cómo gestionar tu cartera con criterio.',
    },
    related: ['que-es-el-interes-compuesto', 'que-es-un-roboadvisor', 'como-invertir-con-poco-dinero'],
  },
  {
    slug: 'que-es-un-roboadvisor',
    title: 'Qué es un roboadvisor y cómo funciona',
    seoTitle: 'Qué es un roboadvisor y cómo funciona',
    description: 'Descubre qué es un roboadvisor, cómo funciona la inversión automatizada, cuáles son los principales en España y si te conviene usar uno.',
    category: 'Dónde invertir',
    published: '2026-04-07',
    updated: '2026-09-10',
    minutes: 11,
    illustration: 'practice',
    cta: {
      title: 'Descubre todas las formas de empezar a invertir',
      body: 'La Guía para Empezar a Invertir compara roboadvisors, fondos indexados y otras opciones para que elijas la que mejor se adapta a tu situación.',
    },
    related: ['que-es-un-fondo-indexado', 'donde-invertir-mi-dinero-opciones-novatos', 'guia-basica-invertir-espana'],
  },
  {
    slug: 'renta-fija-vs-renta-variable',
    title: 'Renta fija vs renta variable',
    seoTitle: 'Renta fija vs renta variable: diferencias clave',
    description: 'Descubre las diferencias entre renta fija y renta variable. Qué es cada una, riesgos, rentabilidad esperada y cómo combinarlas en tu cartera de inversión.',
    category: 'Conceptos básicos',
    published: '2026-04-07',
    updated: '2026-09-10',
    minutes: 10,
    illustration: 'risk',
    cta: {
      title: 'Aprende a construir tu cartera con criterio',
      body: 'En la Guía para Empezar a Invertir te explicamos cómo combinar renta fija y variable, elegir fondos y crear un plan adaptado a tu perfil.',
    },
    related: ['que-es-la-diversificacion', 'que-es-un-fondo-indexado', 'que-es-un-etf'],
  },
  {
    slug: 'msci-world-vs-sp-500',
    title: 'MSCI World vs S&P 500: cuál elegir',
    seoTitle: 'MSCI World vs S&P 500: diferencias y cuál elegir',
    description: 'Comparamos el MSCI World y el S&P 500: qué empresas incluye cada índice, cuánto peso tiene Estados Unidos, qué riesgo asumes y cuál encaja mejor en tu cartera.',
    category: 'Dónde invertir',
    published: '2026-09-10',
    updated: '2026-09-10',
    minutes: 8,
    illustration: 'diversification',
    cta: {
      title: 'Aprende a elegir los fondos de tu cartera',
      body: 'La guía compara fondos globales, americanos y de renta fija, y explica cómo combinarlos según tu horizonte.',
    },
    related: ['que-es-un-fondo-indexado', 'que-es-un-etf', 'cartera-indexada-tres-fondos'],
    faq: [
      {
        question: '¿Es mejor el S&P 500 o el MSCI World?',
        answer: 'El MSCI World reparte la inversión entre 23 países desarrollados y el S&P 500 se concentra en 500 empresas estadounidenses. El S&P 500 ha dado más rentabilidad histórica, con más riesgo de concentración. Para empezar, un fondo global está más diversificado.',
      },
      {
        question: '¿El MSCI World incluye mercados emergentes?',
        answer: 'No. El MSCI World solo incluye países desarrollados. Para añadir emergentes necesitas un fondo específico del MSCI Emerging Markets o un índice global que ya los incluya.',
      },
      {
        question: '¿Puedo combinar los dos índices?',
        answer: 'Sí, es una opción habitual: un fondo global como base y un fondo americano para dar más peso a Estados Unidos. Lo importante es mantener el reparto elegido y no cambiarlo según cuál lo haya hecho mejor.',
      },
    ],
  },
  {
    slug: 'cartera-indexada-tres-fondos',
    title: 'Cómo construir una cartera indexada con tres fondos',
    seoTitle: 'Cartera indexada con tres fondos: guía práctica',
    description: 'Aprende a montar una cartera indexada sencilla con tres fondos, qué porcentaje dedicar a cada uno según tu horizonte y cómo rebalancear sin pagar impuestos.',
    category: 'Dónde invertir',
    published: '2026-09-10',
    updated: '2026-09-10',
    minutes: 9,
    illustration: 'diversification',
    cta: {
      title: 'Construye tu cartera con criterio',
      body: 'La guía explica en detalle cómo elegir fondos, repartir el riesgo y rebalancear sin cometer los errores habituales.',
    },
    related: ['que-es-un-fondo-indexado', 'renta-fija-vs-renta-variable', 'fiscalidad-fondos-indexados-espana'],
    faq: [
      {
        question: '¿Cuántos fondos necesita una cartera indexada?',
        answer: 'Para empezar bastan dos o tres: renta variable global desarrollada, mercados emergentes y renta fija. Añadir más productos no mejora automáticamente el resultado y aumenta las comisiones.',
      },
      {
        question: '¿Cada cuánto hay que rebalancear la cartera?',
        answer: 'Una vez al año es suficiente. Si algún bloque se ha desviado más de cinco puntos de tu objetivo, ajusta dirigiendo las nuevas aportaciones al bloque que se ha quedado corto.',
      },
      {
        question: '¿Por qué rebalancear con aportaciones y no vendiendo?',
        answer: 'Porque en España los fondos de inversión permiten traspasar dinero entre ellos sin tributar, pero vender con ganancias genera una plusvalía que debes declarar. Aportar al bloque rezagado evita ese coste.',
      },
    ],
  },
  {
    slug: 'dca-invertir-cada-mes',
    title: 'DCA: invertir la misma cantidad cada mes',
    seoTitle: 'DCA: invertir cada mes la misma cantidad',
    description: 'Qué es el DCA o inversión periódica, por qué funciona mejor de lo que parece, en qué casos no supera a invertir de golpe y cómo automatizar tus aportaciones.',
    category: 'Primeros pasos',
    published: '2026-09-10',
    updated: '2026-09-10',
    minutes: 7,
    illustration: 'compound',
    cta: {
      title: 'Convierte la constancia en tu ventaja',
      body: 'La guía explica el interés compuesto y la inversión periódica con ejemplos sencillos y un plan de acción.',
    },
    related: ['que-es-el-interes-compuesto', 'como-invertir-con-poco-dinero', 'psicologia-del-inversor'],
    faq: [
      {
        question: '¿El DCA es mejor que invertir todo de golpe?',
        answer: 'En términos históricos, invertir todo de una vez supera al DCA en la mayoría de periodos, porque los mercados pasan más tiempo subiendo. El DCA reduce el riesgo de entrar justo antes de una caída y encaja con dinero que llega poco a poco.',
      },
      {
        question: '¿Qué pasa si el mercado cae mientras hago DCA?',
        answer: 'Que tus aportaciones compran más participaciones al mismo precio. Si mantienes el plan, la caída juega a tu favor durante la fase de acumulación.',
      },
      {
        question: '¿Cuánto hay que aportar cada mes?',
        answer: 'Lo que puedas mantener de forma sostenible después de cubrir tus gastos y tu fondo de emergencia. Es mejor una cantidad pequeña y constante que una grande que tengas que interrumpir.',
      },
    ],
  },
  {
    slug: 'cuanto-puedo-ganar-invirtiendo-100-euros-al-mes',
    title: 'Cuánto puedo ganar invirtiendo 100 euros al mes',
    seoTitle: 'Cuánto puedo ganar invirtiendo 100 € al mes',
    description: 'Tabla de resultados invirtiendo 100 euros al mes durante 10, 20, 30 y 40 años con distintas rentabilidades, y qué factores reducen el resultado final.',
    category: 'Primeros pasos',
    published: '2026-09-10',
    updated: '2026-09-10',
    minutes: 8,
    illustration: 'compound',
    cta: {
      title: 'Haz tus propias cuentas',
      body: 'La calculadora de interés compuesto te deja introducir tus cifras y ver el resultado año a año.',
    },
    related: ['que-es-el-interes-compuesto', 'dca-invertir-cada-mes', 'como-invertir-con-poco-dinero'],
    faq: [
      {
        question: '¿Cuánto se gana invirtiendo 100 euros al mes durante 30 años?',
        answer: 'Con una rentabilidad constante del 6 % anual, unos 100.452 euros, de los que 36.000 los habrías aportado tú. Con un 4 % serían unos 69.405 euros y con un 8 %, unos 149.036 euros.',
      },
      {
        question: '¿Estos cálculos incluyen la inflación?',
        answer: 'No. Son cifras nominales. Para aproximar el poder adquisitivo real, resta la inflación media anual a la rentabilidad que hayas supuesto.',
      },
      {
        question: '¿Qué rentabilidad es realista esperar?',
        answer: 'Nadie puede saberlo. Para hacer cuentas prudentes se suele trabajar con escenarios del 4 % al 7 % anual para una cartera global diversificada a largo plazo, sabiendo que ningún año se parecerá a la media.',
      },
    ],
  },
  {
    slug: 'simulador-de-bolsa-como-practicar',
    title: 'Simulador de bolsa: cómo practicar sin arriesgar dinero',
    seoTitle: 'Simulador de bolsa: practicar sin arriesgar dinero',
    description: 'Qué es un simulador de bolsa, qué se aprende de verdad practicando con dinero ficticio, cuáles son sus límites y cómo usarlo para mejorar tus decisiones reales.',
    category: 'Primeros pasos',
    published: '2026-09-10',
    updated: '2026-09-10',
    minutes: 8,
    illustration: 'practice',
    cta: {
      title: 'Practica con una cartera virtual',
      body: 'La app incluye los 20 capítulos de la guía y una cartera simulada con precios de mercado para aplicar lo aprendido.',
    },
    related: ['psicologia-del-inversor', 'errores-comunes-invertir-principiantes', 'app-para-aprender-a-invertir'],
    faq: [
      {
        question: '¿Un simulador de bolsa sirve para aprender de verdad?',
        answer: 'Sirve para entender los mecanismos y para entrenar la reacción emocional ante las caídas, aunque no reproduce el miedo a perder dinero real ni los impuestos. Como entrenamiento previo es muy útil.',
      },
      {
        question: '¿Puedo perder dinero con un simulador?',
        answer: 'No. Las operaciones y el saldo son ficticios y no se ejecutan en ningún mercado real. Lo que puedes perder es tiempo si practicas sin un plan escrito.',
      },
      {
        question: '¿Cuánto tiempo conviene practicar antes de invertir de verdad?',
        answer: 'No hay un plazo fijo. Un buen criterio es practicar hasta que puedas explicar por qué tienes cada posición y qué harías si la cartera cayera un 30 %.',
      },
    ],
  },
  {
    slug: 'psicologia-del-inversor',
    title: 'Psicología del inversor: por qué vendes en el peor momento',
    seoTitle: 'Psicología del inversor: los sesgos que cuestan dinero',
    description: 'Aversión a la pérdida, sesgo de recencia, efecto manada y exceso de confianza: los sesgos que explican por qué compramos caro y vendemos barato, y cómo evitarlos.',
    category: 'Conceptos básicos',
    published: '2026-09-10',
    updated: '2026-09-10',
    minutes: 9,
    illustration: 'risk',
    cta: {
      title: 'Aprende a gestionar el riesgo y las emociones',
      body: 'La guía dedica capítulos al riesgo, la volatilidad y la relación entre la rentabilidad y lo que puedes aguantar.',
    },
    related: ['errores-comunes-invertir-principiantes', 'dca-invertir-cada-mes', 'simulador-de-bolsa-como-practicar'],
    faq: [
      {
        question: '¿Por qué vendo cuando el mercado cae?',
        answer: 'Por la aversión a la pérdida: perder duele aproximadamente el doble de lo que alegra ganar, así que vender hace que el dolor parezca terminar. Es una reacción emocional, no una decisión de inversión.',
      },
      {
        question: '¿Cómo evito tomar decisiones impulsivas?',
        answer: 'Escribiendo el plan antes de invertir, automatizando las aportaciones y revisando la cartera una vez al año en lugar de cada día. Las reglas decididas en frío son la mejor protección.',
      },
      {
        question: '¿Es mejor no mirar la cartera?',
        answer: 'Revisarla a diario no mejora el resultado y aumenta la sensación de riesgo. Con un horizonte largo, basta con una revisión anual para rebalancear.',
      },
    ],
  },
  {
    slug: 'fiscalidad-fondos-indexados-espana',
    title: 'Fiscalidad de los fondos indexados en España',
    seoTitle: 'Fiscalidad de los fondos indexados en España',
    description: 'Cómo tributan los fondos indexados en España: traspaso sin tributar, tramos del ahorro del 19 % al 28 %, compensación de pérdidas y acumulación frente a distribución.',
    category: 'Inversión en España',
    published: '2026-09-10',
    updated: '2026-09-10',
    minutes: 10,
    illustration: 'book',
    cta: {
      title: 'Entiende el coste real de invertir',
      body: 'La guía dedica un capítulo a los costes y otro a los tipos de interés: dos factores que se llevan buena parte del resultado.',
    },
    related: ['que-es-un-etf', 'que-es-un-fondo-indexado', 'plan-de-pensiones-o-fondo-indexado'],
    faq: [
      {
        question: '¿Se paga algo al traspasar un fondo a otro fondo?',
        answer: 'No. En España los traspasos entre fondos de inversión no tributan: la ganancia queda diferida hasta que reembolsas el dinero a tu cuenta. Los ETF no tienen esta ventaja.',
      },
      {
        question: '¿Qué porcentaje se paga al vender un fondo con ganancias?',
        answer: 'Entre el 19 % y el 28 % de la ganancia, por tramos: 19 % hasta 6.000 €, 21 % hasta 50.000 €, 23 % hasta 200.000 €, 27 % hasta 300.000 € y 28 % por encima.',
      },
      {
        question: '¿Es mejor un fondo de acumulación o de distribución?',
        answer: 'Para construir patrimonio a largo plazo, la acumulación suele ser más eficiente: el fondo reinvierte los dividendos y no generas un evento fiscal cada año.',
      },
    ],
  },
  {
    slug: 'plan-de-pensiones-o-fondo-indexado',
    title: 'Plan de pensiones o fondo indexado',
    seoTitle: 'Plan de pensiones o fondo indexado: qué elegir',
    description: 'Comparamos el plan de pensiones y el fondo indexado: desgravación, límites de aportación, comisiones, flexibilidad y en qué casos conviene cada uno.',
    category: 'Inversión en España',
    published: '2026-09-10',
    updated: '2026-09-10',
    minutes: 9,
    illustration: 'emergency',
    cta: {
      title: 'Ordena tus prioridades financieras',
      body: 'La guía explica qué hacer primero —colchón, deudas, inversión— y cómo encajar cada producto en un plan con sentido.',
    },
    related: ['fiscalidad-fondos-indexados-espana', 'cartera-indexada-tres-fondos', 'que-es-un-fondo-indexado'],
    faq: [
      {
        question: '¿Cuánto puedo aportar a un plan de pensiones y desgravar?',
        answer: 'El límite individual es de 1.500 euros al año, y de hasta 10.000 euros si la aportación procede de la empresa. Las aportaciones reducen la base imponible general.',
      },
      {
        question: '¿Qué es mejor, plan de pensiones o fondo indexado?',
        answer: 'Depende de tu tipo marginal y de tu horizonte. El plan de pensiones desgrava hoy, pero tributa al rescatarlo como rendimiento del trabajo y es menos flexible. El fondo indexado no desgrava, pero permite disponer del dinero y ajustar la cartera sin coste fiscal.',
      },
      {
        question: '¿Cuándo puedo rescatar un plan de pensiones?',
        answer: 'En supuestos concretos: jubilación, desempleo de larga duración, enfermedad grave, fallecimiento o dependencia, entre otros. No es un producto pensado para disponer del dinero a voluntad.',
      },
    ],
  },
  {
    slug: 'que-son-los-dividendos',
    title: 'Qué son los dividendos y cómo funcionan',
    seoTitle: 'Qué son los dividendos y cómo funcionan',
    description: 'Aprende qué es un dividendo, cómo se calcula la rentabilidad por dividendo, qué pasa el día ex-dividendo, cómo tributan en España y qué alternativas tienes.',
    category: 'Conceptos básicos',
    published: '2026-09-10',
    updated: '2026-09-10',
    minutes: 8,
    illustration: 'concepts',
    cta: {
      title: 'Entiende cómo se genera la rentabilidad',
      body: 'La guía explica de dónde vienen los rendimientos y por qué reinvertirlos marca la diferencia a largo plazo.',
    },
    related: ['que-es-el-interes-compuesto', 'que-es-un-etf', 'que-es-la-diversificacion'],
    faq: [
      {
        question: '¿Los dividendos son dinero gratis?',
        answer: 'No. El día ex-dividendo el precio de la acción baja aproximadamente el importe repartido, porque ese dinero sale del balance de la empresa. El dividendo es parte del rendimiento total, no un extra.',
      },
      {
        question: '¿Cuánto tributan los dividendos en España?',
        answer: 'Como ganancias del ahorro, con los mismos tramos que las plusvalías: del 19 % al 28 % según el importe anual, con retención en el momento del cobro.',
      },
      {
        question: '¿Una rentabilidad por dividendo alta es buena señal?',
        answer: 'No necesariamente. Un porcentaje muy alto suele indicar que el precio ha caído porque el mercado espera un recorte del dividendo. Conviene mirar también el porcentaje del beneficio que se reparte.',
      },
    ],
  },
  {
    slug: 'app-para-aprender-a-invertir',
    title: 'Cómo elegir una app para aprender a invertir',
    seoTitle: 'App para aprender a invertir: cómo elegirla',
    description: 'Cinco criterios para distinguir una app educativa de un producto especulativo, qué se aprende practicando con dinero ficticio y qué límites conviene tener claros.',
    category: 'Primeros pasos',
    published: '2026-09-10',
    updated: '2026-09-10',
    minutes: 7,
    illustration: 'learn',
    cta: {
      title: 'Conoce nuestra app por dentro',
      body: 'EAI combina los 20 capítulos de la guía con un buscador de activos y una cartera simulada de 10.000 USD.',
    },
    related: ['simulador-de-bolsa-como-practicar', 'como-empezar-a-invertir-desde-cero', 'psicologia-del-inversor'],
    faq: [
      {
        question: '¿Qué debe tener una buena app para aprender a invertir?',
        answer: 'Contenido educativo que explique conceptos antes de operar, separación clara entre dinero real y simulado, ausencia de promesas de rentabilidad y explicación honesta de sus límites.',
      },
      {
        question: '¿Sirve de algo practicar con dinero ficticio?',
        answer: 'Sí, para entender los mecanismos y entrenar la reacción ante las caídas. No reproduce el miedo a perder dinero real ni los impuestos, así que no sustituye a la experiencia, pero reduce los errores de principiante.',
      },
      {
        question: '¿Se puede aprender a invertir sin usar ninguna app?',
        answer: 'Por supuesto. Un buen libro, artículos como los de este blog y una hoja de cálculo cubren los fundamentos. La app es una forma cómoda de practicar, no un requisito.',
      },
    ],
  },
];

export const articleBySlug = new Map(articles.map(article => [article.slug, article]));
